# Generated by Django 4.0.4 on 2022-05-06 04:28

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=50)),
                ('function_parameters', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('function_description', models.CharField(blank=True, max_length=500)),
                ('function_returns', models.CharField(max_length=200)),
                ('function_examples', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('function_called_by', models.ManyToManyField(blank=True, to='generator.function')),
                ('function_calls', models.ManyToManyField(blank=True, to='generator.function')),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_name', models.CharField(max_length=50)),
                ('import_path', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=50)),
                ('variable_type', models.CharField(blank=True, max_length=20)),
                ('variable_value', models.CharField(blank=True, max_length=500)),
                ('variable_scope', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ManyToManyField(blank=True, default='global', to='generator.function')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=500)),
                ('project_path', models.FileField(upload_to='projects/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('functions', models.ManyToManyField(blank=True, to='generator.function')),
                ('imports', models.ManyToManyField(blank=True, to='generator.import')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variables', models.ManyToManyField(blank=True, to='generator.variable')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=50)),
                ('interface_extends', models.CharField(max_length=50)),
                ('interface_parameters', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ManyToManyField(blank=True, default='global', to='generator.variable')),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='imported_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.import'),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('active_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='generator.project')),
                ('projects', models.ManyToManyField(blank=True, to='generator.project')),
            ],
        ),
    ]
